// <auto-generated />
namespace DevReadyAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Course_Enrollment_AddNewProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_Enrollment_AddNewProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201807231501506_Course_Enrollment_AddNewProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
