// <auto-generated />
namespace DevReadyAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_AddPhoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_AddPhoto));
        
        string IMigrationMetadata.Id
        {
            get { return "201809292114476_Student_AddPhoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
