// <auto-generated />
namespace DevReadyAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Course_Enhancements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_Enhancements));
        
        string IMigrationMetadata.Id
        {
            get { return "201808121250237_Course_Enhancements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
