// <auto-generated />
namespace DevReadyAcademy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Course_Student_AddNewPropertiesAndValidations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Course_Student_AddNewPropertiesAndValidations));
        
        string IMigrationMetadata.Id
        {
            get { return "201808061916473_Course_Student_AddNewPropertiesAndValidations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
